
GET http://localhost:3003/api/blogs

### careful with POST, do not add an empty line before the headers
POST http://localhost:3003/api/blogs/ 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRob21hcyIsImlkIjoiNjhhNDcxYjU3MTZhYTQ0MzBlYzA1ODhmIiwiaWF0IjoxNzU1NjExODg3LCJleHAiOjE3NTU2MTU0ODd9.Vp6AoRzdm_VoeSlVzTIbFFCOFXfkitUM3Oz5oh63m6s

{
  "title": "blog1",
  "author": "t1t1",
  "url": "testURL",
  "user": "",
  "likes": 1
}

###
POST http://localhost:3003/api/blogs/ 
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRob21hcyIsImlkIjoiNjhhNDcxYjU3MTZhYTQ0MzBlYzA1ODhmIiwiaWF0IjoxNzU1NjExODg3LCJleHAiOjE3NTU2MTU0ODd9.Vp6AoRzdm_VoeSlVzTIbFFCOFXfkitUM3Oz5oh63m6s
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF5YW1lIiwiaWQiOiI2OGE0NzI1OTkyOWE2ZGNkNWRkNjM4ZmUiLCJpYXQiOjE3NTU2MTM0NDYsImV4cCI6MTc1NTYxNzA0Nn0.SWPTl4yyCkz4Q-HtAZAOCg7PiWv_WtksDfbn4ey0cNg

{
  "title": "blog2",
  "author": "t2t2",
  "url": "testURL",
  "likes": 2
}

###
DELETE http://localhost:3003/api/blogs/68a48d8ce52b5322584a2a00
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRob21hcyIsImlkIjoiNjhhNDcxYjU3MTZhYTQ0MzBlYzA1ODhmIiwiaWF0IjoxNzU1NjExODg3LCJleHAiOjE3NTU2MTU0ODd9.Vp6AoRzdm_VoeSlVzTIbFFCOFXfkitUM3Oz5oh63m6s
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF5YW1lIiwiaWQiOiI2OGE0NzI1OTkyOWE2ZGNkNWRkNjM4ZmUiLCJpYXQiOjE3NTU2MTM0NDYsImV4cCI6MTc1NTYxNzA0Nn0.SWPTl4yyCkz4Q-HtAZAOCg7PiWv_WtksDfbn4ey0cNg
